import Link from "next/link";
import "./globals.css";
import { Edit } from "./edit";
/*Clinet Component import { useEffect,useState } from "react"; */

export const metadata = {
  title: "Development Study",
  description: "Generated by Thomas",
};
export default async function RootLayout({ children }) {
  const darren = await fetch(`${process.env.NEXT_PUBLIC_API_URL2}cellStaffs/${id}`)
  const topics = await darren.json();

  const conCell = await fetch(`${process.env.NEXT_PUBLIC_API_URL1}cellStaffs/${id}`)
  const cellStaffs = await conCell.json();
  /*Clinet Component
  const [topics, setTopics] = useState([]);
  useEffect(()=>{
    fetch('http://localhost:9999/topics')
      .then(resp=>resp.json())
      .then(result=>{
        setTopics(result);
      });
  },[]);
  */
  return (
    <html>
      <body>
        <Link href="/"><img src="/logo-library1-1.svg"></img></Link>
        <h1><Link href="/">Web</Link></h1>
        <ol>
          {topics.map(topic=>{
              return <li key={topic.id}><Link href={`/readstack/${topic.id}`}>{topic.title}</Link></li>
            })}
        </ol>
        {children}
        <Edit/>
        <ol>
          {cellStaffs.map(staff=>{
              return <li key={staff.id}><Link href={`/read/${staff.id}`}>{staff.title}</Link></li>
            })}
        </ol>
      </body>
    </html>
  );
}